# Generated by Django 3.2.7 on 2021-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_deleteduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=22)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
    ]
