# Generated by Django 3.2.7 on 2021-10-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_delete_order'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
