# Generated by Django 3.2.7 on 2021-10-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211019_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='update_at',
        ),
    ]
