# Generated by Django 3.2.7 on 2021-10-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_update_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
