# Generated by Django 3.2.7 on 2021-10-19 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0003_food'),
        ('customer', '0001_initial'),
        ('order', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.profile')),
            ],
        ),
    ]
