# Generated by Django 3.2.7 on 2021-10-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing your order'), ('Dispatched', 'Your order is dispatched'), ('Delivered', 'Order is delivered successfully')], default=('Preparing', 'Preparing your order'), max_length=100),
        ),
    ]
